### ISSUE TITLE
Upload source distribution to PyPI

### ISSUE THREAD

**Issue by amyreese** [JelleZijlstra/inspect2#2]
Could you please upload a source distribution of v0.1 to PyPI?  We need this to use inspect2 with our internal packaging system.

**Comment by fornellas** [comment]
FYI, we use it as dependency of [TestSlide](https://github.com/facebookincubator/TestSlide/blob/master/setup.py#L29). `pip install` works outside though, but we need to be able to build things internally.

**Comment by JelleZijlstra** [comment]
Wow I didn't know I had users. I will add an sdist.

**Comment by JelleZijlstra** [comment]
I just uploaded v0.1.1 with an sdist (but without a wheel because pypi refuses to accept it).
